package defensivethinking.co.za.a702podcasts.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFBA9EFF)
val md_theme_dark_onPrimary = Color(0xFF39008C)
val md_theme_dark_primaryContainer = Color(0xFF8455EF)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFFD933D)
val md_theme_dark_onSecondary = Color(0xFF4C2300)
val md_theme_dark_secondaryContainer = Color(0xFF944A00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC5)
val md_theme_dark_tertiary = Color(0xFFFF97B5)
val md_theme_dark_onTertiary = Color(0xFF6A0934)
val md_theme_dark_tertiaryContainer = Color(0xFF8D214B)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF060E20)
val md_theme_dark_onBackground = Color(0xFFDEE5FF)
val md_theme_dark_surface = Color(0xFF060E20)
val md_theme_dark_onSurface = Color(0xFFDEE5FF)
val md_theme_dark_surfaceVariant = Color(0xFF192540)
val md_theme_dark_onSurfaceVariant = Color(0xFFA3AAC4)
val md_theme_dark_outline = Color(0xFF6D758C)
val md_theme_dark_inverseOnSurface = Color(0xFF060E20)
val md_theme_dark_inverseSurface = Color(0xFFDEE5FF)
val md_theme_dark_inversePrimary = Color(0xFF6E3BD7)
val md_theme_dark_surfaceTint = Color(0xFFBA9EFF)
